from __future__ import annotations

from pathlib import Path
from typing import Any

from .fingerprints import sha256_json
from .io import read_json, write_json_atomic, write_text_atomic
from .state import load_or_create, save
from .validation import validate_worker_result


def assemble(workflow_dir: Path, config: dict[str, Any], plan: dict[str, Any]) -> Path:
    state = load_or_create(workflow_dir, str(config["workflow_id"]))
    if any(item["status"] != "validated" for item in state["batches"]):
        raise ValueError("all batches must be validated before assembly")
    if state["planning"].get("sha256") != plan.get("plan_sha256"):
        raise ValueError("assembly plan does not match ledger")
    sections = [f"# {config['workflow_id']} Results", "", "Generated by Context Loom.", ""]
    trace: list[dict[str, Any]] = []
    for task in plan["tasks"]:
        result = read_json(workflow_dir / ".context-loom" / "results" / f"{task['task_id']}.json")
        batch = next(b for b in state["batches"] if task["task_id"] in b["task_ids"])
        validate_worker_result(result, task_id=task["task_id"], baseline_sha256=state["baseline"]["sha256"],
                               packet_sha256=batch["packet_sha256"])
        if result["status"] != "completed":
            raise ValueError(f"cannot assemble a failed task: {task['task_id']}")
        sections += [f"## {task['task_id']}: {task['title']}", "", str(result.get("content", "")).rstrip(), ""]
        trace.append({"task_id": task["task_id"], "batch_id": state["tasks"][task["task_id"]]["batch_id"], "result_file": f"results/{task['task_id']}.json"})
    output = workflow_dir / ".context-loom" / "assembled.md"
    write_text_atomic(output, "\n".join(sections))
    trace_data = {"schema_version": "context-loom/trace-v1", "workflow_id": config["workflow_id"], "tasks": trace}
    write_json_atomic(workflow_dir / ".context-loom" / "trace.json", trace_data)
    state["assembly"] = {"status": "validated", "output": "assembled.md", "sha256": sha256_json(trace_data)}
    save(workflow_dir, state)
    return output
